### ISSUE TITLE
Do these source packages work well with the modern SDK project format?

### ISSUE THREAD

**Issue by ChrisLambrou** [red-gate/MicroLibraries#15]
The last time I worked on any of these libraries, installing a NuGet package means that a macro ran in Visual Studio which copied some source files into your source tree, under an `App_Packages` folder. The expectation was that they would then be added to source control for any consuming project. Definitely icky!

Under the newer dotnet SDK, and indeed modern versions of NuGet, this is no longer possible. Indeed, it was never actually desirable. The ideal behaviour would be that the packages get restored at build time, then the packages source files would get references by the consuming project, but not actually get copied into the project folder.

I tried to make this work in the past, but the NuGet documentation on doing this was rather lacking and I never managed to get something to work well. Maybe it's time to revisit this issue?

**Comment by nyctef** [comment]
I'm going to have a go at using these in RCC: https://github.com/red-gate/RedgateChangeControl/issues/852

**Comment by ChrisLambrou** [comment]
> I'm going to have a go at using these in RCC: [red-gate/RedgateChangeControl#852](https://github.com/red-gate/RedgateChangeControl/issues/852)

Cool! Please let me knw how it goes. :)

**Comment by nyctef** [comment]
Well, serialization seems to just be a drop-in replacement, so that's cool (I'm assuming #13 is the PR that made it work?)

Deserialization is a bit trickier, since the `IDictionary<string, object>` result needs a bit more work to handle compared to Newtonsoft's magic object creation - just working through that [on a branch](https://github.com/red-gate/RedgateChangeControl/compare/use-tinyjsonser) now

**Comment by ChrisLambrou** [comment]
Yeah, serialisation was really easy. Deserialisation is much more of a pain to work with. I've been contemplating writing a single-file deserialisation source library that supports deserialisation to arbitrary object types, but every time I think about it, my head hurts!

Also, neither of those JSON libraries comes with any degree of configurability, by design. I was original just writing a serialiser to replace Json.Net in the Usage Client, so just replicated that behaviour and nothing more. Then the deserialiser came about for parsing simple JSON error responses from the usage endpoints, so it's just not that sophisticated.

**Comment by nyctef** [comment]
Yeah, magic deserialization sounds really tricky to get right. I suspect a `JToken`-style api might be a nicer balance between simplicity and ease of use, but I've not tried it at all.

Still, this library seems to be functioning perfectly as designed so far - thanks for working on it! :)

**Comment by ChrisLambrou** [comment]
Turns out that, yes, they do work. In fact, I thin we're now looking at **only** supporting the modern project format.
